[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc", "ffmpeg-full", "pkg-config"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.start]
cmd = "python src/main.py"
