version: '3.8'

services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: aim_bot
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: aim_bot_db
    environment:
      POSTGRES_DB: aim_bot
      POSTGRES_USER: aim_bot_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: aim_bot_api
    env_file:
      - ../.env
    command: uvicorn src.api.app:create_app --factory --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_data:
